FROM node:10.22.1-alpine3.11

ENV NODE_ENV=dev
WORKDIR /usr/src-app

COPY package*.json ./
RUN npm install -g typescript mocha ts-node tslint cross-env ts-node-dev
RUN npm install

COPY . .

EXPOSE 3000
EXPOSE 7001
CMD [ "npm", "run", "dev" ]